### ISSUE TITLE
Multiple keys remapings - How to contribute

### ISSUE THREAD

**Issue by sandangel** [myfreeweb/evscript#12]
Hi, I would like to help with the feature to allow multiple keys remappings like `<super>c` to `<ctrl>c` or `<alt>Left` to `<ctrl>Left`, those are impossible to remap under Wayland with xkb. Do you think this is possible with evscript and what is the approach for this?

**Comment by valpackett** [comment]
evscript does not remap (unless you want to proxy all keys through it and disable the original keyboard from the compositor). If you're okay with the original key combo also being pressed, that's easy.

**Comment by sandangel** [comment]
Oh I see. Is there a way to disable the event generated by the original keys and only emit the key events that we want? If we can export the function to disable a key event, that should be fairly easy to implement key remap in dyon script

**Comment by valpackett** [comment]
Only if you want to proxy all events and exclude the original keyboard in the compositor.

You can't disable events on an existing keyboard device. evscript (and everything, really) has **read only** access to actual keyboards' `/dev/input/*` entries.

**Comment by sandangel** [comment]
@myfreeweb OK, thank you. I will try a different way since this seen to be a big task
