### ISSUE TITLE
rusty-sandbox moved to crates.io

### ISSUE THREAD

**Issue by ascii78** [myfreeweb/evscript#17]
they also moved away from github:

replacing:
rusty-sandbox = { git = "https://github.com/myfreeweb/rusty-sandbox", branch = "master" }

with:
rusty-sandbox = 0.1.0

worked

**Comment by valpackett** [comment]
that's my crate :D oops

**Comment by valpackett** [comment]
This one is also now https://codeberg.org/valpackett/evscript
