### ISSUE TITLE
example not like xcape

### ISSUE THREAD

**Issue by ascii78** [myfreeweb/evscript#18]
Hi,

Just ran the example, but I can't really get it to work, if I tap caps it does indeed send escape, but it also lights up and then works as a caps lock key. If I use it on left_ctrl it doesn't work. Should it work like xcape ? (havn't used it in a while, before i was using caps2esc on linux).

**Comment by ascii78** [comment]
nevermind works at advertised, I had to set xkb_options ctrl:nocaps in sway as mentioned elsewhere in the issues. Also I had accidently enabled both should_esc and should_lshift at the same time.

**Comment by ascii78** [comment]
nice work

**Comment by valpackett** [comment]
> I had accidently enabled both should_esc and should_lshift at the same time

FYI, these are internal variables of the script that determine whether esc/lshift will be typed on the next event. They are not control knobs :)
